### ISSUE TITLE
Use without database

### ISSUE THREAD

**Issue by Mopster** [amamarul/laravel-json-locations-manager#2]
Can we use this without having to use the database and just update the json translation files ?

**Comment by amamarul** [comment]
Hello!
I can try to make something like this.
Be in mind that this package don't use your main database and you can use only in dev mode. Some projects has a lot of langs and strings.

**Comment by Mopster** [comment]
Yeah we're looking for a web interface that doesn't use the main database. Sqlite is a solution we're ok with.  We'll want to make the interface also available on production, we'll need to have a look to make the routes secure.

I'll close this since it's no longer an issue for us. :-)

**Comment by amamarul** [comment]
Hello, you can use this package in production, in fact was made for that. See the instructions, in config file you can add your middlewares and change the prefix routes.

> ## In the config file you can call your custom layout, the content section and the scripts section (this is important for the edit views) and routes prefix and middlewares.
> ### Routes middlewares
> in config file you can add your middlewares, by default is only 'web' middleware
in config file: (you need to run the publish command `$ php artisan vendor:publish --provider='Amamarul\LaravelJsonLocationsManager\Providers\LaravelJsonLocationsManagerServiceProvider'`)
``` 
       /**
         * Routes
         */
        'prefix' => 'translations',
        'middlewares' => ['web'],
```
- to change the prefix route you can change "translations" to something different
- to add a middelware you can put for example  ['web','admin']

I hope you can use in production and i would like to hear your experience.
Regards,
Maru
