### ISSUE TITLE
"Are you sure you want to create a new language?" when adding a new string

### ISSUE THREAD

**Issue by Mopster** [amamarul/laravel-json-locations-manager#4]
When adding a new string, a confirmation box pops up with "Are you sure you want to create a new language?"

**Comment by amamarul** [comment]
Hello!
Ok, i will correct that. Thanks!

**Comment by Mopster** [comment]
Oh, I just noticed that the the 'New language' buttons has "Are you sure you want to create a new string?". Looks like they got switched around. :-)
