### ISSUE TITLE
Error when saving translations

### ISSUE THREAD

**Issue by Mopster** [amamarul/laravel-json-locations-manager#5]
When trying to save a new translation, it gives a MethodNotAllowedHttpException

<div id="sf-resetcontent" class="sf-reset">
<h1>Whoops, looks like something went wrong.</h1>
<h2 class="block_exception clear_fix">
<span class="exception_counter">1/1</span>
<span class="exception_title"><abbr title="Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException">MethodNotAllowedHttpException</abbr> in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php line 233">RouteCollection.php line 233</a>:</span>
<span class="exception_message"></span>
</h2>
<div class="block">
<ol class="traces list_exception">
<li> in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php line 233">RouteCollection.php line 233</a></li>
<li>at <abbr title="Illuminate\Routing\RouteCollection">RouteCollection</abbr>->methodNotAllowed(<em>array</em>('GET', 'HEAD')) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php line 220">RouteCollection.php line 220</a></li>
<li>at <abbr title="Illuminate\Routing\RouteCollection">RouteCollection</abbr>->getRouteForMethods(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>), <em>array</em>('GET', 'HEAD')) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php line 158">RouteCollection.php line 158</a></li>
<li>at <abbr title="Illuminate\Routing\RouteCollection">RouteCollection</abbr>->match(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Router.php line 533">Router.php line 533</a></li>
<li>at <abbr title="Illuminate\Routing\Router">Router</abbr>->findRoute(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Router.php line 512">Router.php line 512</a></li>
<li>at <abbr title="Illuminate\Routing\Router">Router</abbr>->dispatchToRoute(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Router.php line 498">Router.php line 498</a></li>
<li>at <abbr title="Illuminate\Routing\Router">Router</abbr>->dispatch(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php line 174">Kernel.php line 174</a></li>
<li>at <abbr title="Illuminate\Foundation\Http\Kernel">Kernel</abbr>->Illuminate\Foundation\Http\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php line 30">Pipeline.php line 30</a></li>
<li>at <abbr title="Illuminate\Routing\Pipeline">Pipeline</abbr>->Illuminate\Routing\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php line 51">Debugbar.php line 51</a></li>
<li>at <abbr title="Barryvdh\Debugbar\Middleware\Debugbar">Debugbar</abbr>->handle(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>), <em>object</em>(<abbr title="Closure">Closure</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php line 148">Pipeline.php line 148</a></li>
<li>at <abbr title="Illuminate\Pipeline\Pipeline">Pipeline</abbr>->Illuminate\Pipeline\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php line 53">Pipeline.php line 53</a></li>
<li>at <abbr title="Illuminate\Routing\Pipeline">Pipeline</abbr>->Illuminate\Routing\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php line 46">CheckForMaintenanceMode.php line 46</a></li>
<li>at <abbr title="Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode">CheckForMaintenanceMode</abbr>->handle(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>), <em>object</em>(<abbr title="Closure">Closure</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php line 148">Pipeline.php line 148</a></li>
<li>at <abbr title="Illuminate\Pipeline\Pipeline">Pipeline</abbr>->Illuminate\Pipeline\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php line 53">Pipeline.php line 53</a></li>
<li>at <abbr title="Illuminate\Routing\Pipeline">Pipeline</abbr>->Illuminate\Routing\{closure}(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php line 102">Pipeline.php line 102</a></li>
<li>at <abbr title="Illuminate\Pipeline\Pipeline">Pipeline</abbr>->then(<em>object</em>(<abbr title="Closure">Closure</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php line 149">Kernel.php line 149</a></li>
<li>at <abbr title="Illuminate\Foundation\Http\Kernel">Kernel</abbr>->sendRequestThroughRouter(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php line 116">Kernel.php line 116</a></li>
<li>at <abbr title="Illuminate\Foundation\Http\Kernel">Kernel</abbr>->handle(<em>object</em>(<abbr title="Illuminate\Http\Request">Request</abbr>)) in <a title="C:\laragon\www\broadsoft\public\index.php line 53">index.php line 53</a></li>
</ol>
</div>

**Comment by amamarul** [comment]
Hello!
I´m testing and i don´t have that error. When exactly you have this error?

**Comment by Mopster** [comment]
Hmm I'm also unable to reproduce, strange, it might've been the result of me messing around.

I'll close this one.
